// Command stracegen copies argument classifications from the pinned gVisor
// module. It does not import gVisor into the host module or modify its sources.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "gvisor.dev/gvisor").Output()
	if err != nil {
		return err
	}
	root := strings.TrimSpace(string(out))
	for _, arch := range []string{"amd64", "arm64"} {
		file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(root, "pkg/sentry/strace/linux64_"+arch+".go"), nil, parser.ParseComments)
		if err != nil {
			return err
		}
		var b bytes.Buffer
		for _, comment := range file.Comments[0].List {
			fmt.Fprintln(&b, comment.Text)
		}
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "// Code generated by go run ./internal/stracegen from gVisor strace; DO NOT EDIT.")
		fmt.Fprintln(&b, "\npackage main\n\nvar syscallFormats = map[uint64]syscallFormat{")
		var generationError error
		count := 0
		ast.Inspect(file, func(n ast.Node) bool {
			entry, ok := n.(*ast.KeyValueExpr)
			if !ok {
				return true
			}
			call, ok := entry.Value.(*ast.CallExpr)
			if !ok {
				return true
			}
			fn, ok := call.Fun.(*ast.Ident)
			if !ok || fn.Name != "makeSyscallInfo" {
				return true
			}
			number, ok := entry.Key.(*ast.BasicLit)
			if !ok || number.Kind != token.INT || len(call.Args) == 0 || len(call.Args) > 7 {
				generationError = fmt.Errorf("unsupported strace table entry in %s", arch)
				return false
			}
			name, ok := call.Args[0].(*ast.BasicLit)
			if !ok || name.Kind != token.STRING {
				generationError = fmt.Errorf("unsupported strace name in %s", arch)
				return false
			}
			fmt.Fprintf(&b, "%s: {name: %s, args: []string{", number.Value, name.Value)
			for index, arg := range call.Args[1:] {
				kind, ok := arg.(*ast.Ident)
				if !ok {
					generationError = fmt.Errorf("unsupported argument format in %s", arch)
					return false
				}
				switch kind.Name {
				case "OpenHow", "WriteBuffer", "SockAddr", "SetSockOptVal":
					if index+2 >= len(call.Args) {
						generationError = fmt.Errorf("missing size following %s in %s", kind.Name, arch)
						return false
					}
				}
				fmt.Fprintf(&b, "%s,", strconv.Quote(kind.Name))
			}
			fmt.Fprintln(&b, "}},")
			count++
			return false
		})
		if generationError != nil {
			return generationError
		}
		if count == 0 {
			return fmt.Errorf("no strace entries in %s", arch)
		}
		fmt.Fprintln(&b, "}")
		data, err := format.Source(b.Bytes())
		if err != nil {
			return err
		}
		if err := os.WriteFile("strace_"+arch+".go", data, 0644); err != nil {
			return err
		}
	}
	return nil
}
